name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: clone deployment repo
      run: git clone https://github.com/consindo/consindo.github.io.git .deploy-git
    - name: restore packages      
      run: npm ci 
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    - name: git config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: render & push
      env:
        GITHUB_ACTOR: consindo
      run: npm run deploy
